In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/playground-series-s6e10/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e10/train.csv
/kaggle/input/competitions/playground-series-s6e10/test.csv

In [2]:
train_df = pd.read_csv("/kaggle/input/competitions/playground-series-s6e10/train.csv")
test_df = pd.read_csv("/kaggle/input/competitions/playground-series-s6e10/test.csv")
sample_df = pd.read_csv("/kaggle/input/competitions/playground-series-s6e10/sample_submission.csv")

In [3]:
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)


display(train_df.head())
display(train_df.info())

display(sample_df.head())

Train shape: (699635, 23)
Test shape: (299844, 22)

,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender,Customer Type,Type of Travel,Class,satisfaction
0,0,36,694,4,4,4,3,1,4,1,...,4,3,1,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
1,1,56,651,5,5,5,5,5,4,4,...,5,4,3,0,0.0,Male,Loyal Customer,Business travel,Business,True
2,2,31,1371,3,4,2,5,3,3,3,...,4,5,3,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
3,3,10,1616,3,5,3,3,3,3,3,...,3,4,3,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False
4,4,23,481,3,4,3,4,5,3,5,...,5,3,5,5,0.0,Female,disloyal Customer,Business travel,Eco,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699635 entries, 0 to 699634
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id                                 699635 non-null  int64
 1   Age                                699635 non-null  int64
 2   Flight Distance                    699635 non-null  int64
 3   Inflight wifi service              699635 non-null  int64
 4   Departure/Arrival time convenient  699635 non-null  int64
 5   Ease of Online booking             699635 non-null  int64
 6   Gate location                      699635 non-null  int64
 7   Food and drink                     699635 non-null  int64
 8   Online boarding                    699635 non-null  int64
 9   Seat comfort                       699635 non-null  int64
 10  Inflight entertainment             699635 non-null  int64
 11  On-board service                   699635 non-null  int64
 12  Leg room service                   699635 non-null  int64
 13  Baggage handling                   699635 non-null  int64
 14  Checkin service                    699635 non-null  int64
 15  Cleanliness                        699635 non-null  int64
 16  Departure Delay in Minutes         699635 non-null  int64
 17  Arrival Delay in Minutes           699343 non-null  float64
 18  Gender                             699635 non-null  object
 19  Customer Type                      699635 non-null  object
 20  Type of Travel                     699635 non-null  object
 21  Class                              699635 non-null  object
 22  satisfaction                       699635 non-null  bool
dtypes: bool(1), float64(1), int64(17), object(4)
memory usage: 118.1+ MB

None

       id  satisfaction
0  699635      0.443573
1  699636      0.443573
2  699637      0.443573
3  699638      0.443573
4  699639      0.443573

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699635 entries, 0 to 699634
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id                                 699635 non-null  int64
 1   Age                                699635 non-null  int64
 2   Flight Distance                    699635 non-null  int64
 3   Inflight wifi service              699635 non-null  int64
 4   Departure/Arrival time convenient  699635 non-null  int64
 5   Ease of Online booking             699635 non-null  int64
 6   Gate location                      699635 non-null  int64
 7   Food and drink                     699635 non-null  int64
 8   Online boarding                    699635 non-null  int64
 9   Seat comfort                       699635 non-null  int64
 10  Inflight entertainment             699635 non-null  int64
 11  On-board service                   699635 non-null  int64
 12  Leg room service                   699635 non-null  int64
 13  Baggage handling                   699635 non-null  int64
 14  Checkin service                    699635 non-null  int64
 15  Cleanliness                        699635 non-null  int64
 16  Departure Delay in Minutes         699635 non-null  int64
 17  Arrival Delay in Minutes           699343 non-null  float64
 18  Gender                             699635 non-null  object
 19  Customer Type                      699635 non-null  object
 20  Type of Travel                     699635 non-null  object
 21  Class                              699635 non-null  object
 22  satisfaction                       699635 non-null  bool
dtypes: bool(1), float64(1), int64(17), object(4)
memory usage: 118.1+ MB

In [5]:
train_df.isnull().sum()

id                                     0
Age                                    0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             292
Gender                                 0
Customer Type                          0
Type of Travel                         0
Class                                  0
satisfaction                           0
dtype: int64

In [6]:
print("Duplicated rows:", train_df.duplicated().sum())

Duplicated rows: 0

In [7]:
#Target Distribution

print(train_df["satisfaction"].value_counts())

print(train_df["satisfaction"].value_counts(normalize=True))

satisfaction
False    389296
True     310339
Name: count, dtype: int64
satisfaction
False    0.556427
True     0.443573
Name: proportion, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split

target = "satisfaction"

X = train_df.drop(columns=[target])
y = train_df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42,stratify=y
)

print(X_train.shape, X_test.shape)

(559708, 22) (139927, 22)